### ISSUE TITLE
Converting .obj with multiple texture files?

### ISSUE THREAD

**Issue by PaulCapestany** [ricardo-rendoncepeda/mtl2opengl#2]
Is `mtl2opengl.pl` supposed to be able to handle converting .obj & .mtl files that reference multiple different texture files?

I was able to get the Pyramid demo working just fine, but then tried stepping things up by converting this [Blonde Girl .obj](http://www.turbosquid.com/FullPreview/Index.cfm/ID/699654) file, and the generated OBJ.h ends up not having a OBJNormals [] value.

I've only ever used Perl for writing regexes, so any help would be awesome

**Comment by ricardo-rendoncepeda** [comment]
Hey @PaulCapestany!

The script wasn't designed with multiple textures in mind, but I'll look into it as soon as I can (probably this weekend). I've used the Blonde Girl model before, but never with mtl2opengl. The OBJ and MTL files are arranged in an unconventional manner, but it seems like a fun challenge!

**Comment by ricardo-rendoncepeda** [comment]
@PaulCapestany 

I've had a look and there are actually two issues here. One has been solved and the other is unfortunately not supported at the time:

1) Missing Normals
Your generated OBJ.h file does not have an OBJNormals[] value because the model you're using was exported without normals. Code could be written to automatically generate normals for every triangular face, but a much easier solution is to open up the .obj file in your 3D modeling software of choice (e.g. Maya or Blender) and re-export the model with normals.
You can find the updated model for Blonde Girl below:
http://www.filefactory.com/file/6k00vibipumf/BlondeGirl_zip

2) Multiple Textures
Multiple textures are possible to implement with a few tweaks. Unfortunately, since this wasn't the original goal of mtl2opengl, this feature will remain missing for the time being. I do have a tutorial coming out soon on http://raywenderlich.com/ that teaches you how develop a similar tool to mtl2opengl, so hopefully that'll help!

Anyway, this is what your model looks like with full geometry, no materials, and a single texture. Sorry to fuel your nightmares...

![ios simulator screen shot oct 6 2013 4 27 28 pm](https://f.cloud.github.com/assets/2679204/1277787/de3f60ba-2ee0-11e3-8e1e-3be23c709bc8.png)

**Comment by PaulCapestany** [comment]
@ricardo-rendoncepeda — cool, appreciate your response.

I'm totally new to all of this 3D/OpenGL stuff, and have been sort of surprised at how little coherent (and up-to-date) info I've been able to find to get what I'd think would be really basic things done with OpenGL on iOS. This project has been really useful to me as-is already though, so thanks! (I definitely look forward to checking out your upcoming tutorial as well)

I take it you've come across [Jeff Lamarche's](http://iphonedevelopment.blogspot.com/2011/04/blender-257-objective-c-export-script.html) Blender [Objective-C Export script](https://github.com/jlamarche/iOS-OpenGLES-Stuff)? As a newbie it seemed really promising to me, but unfortunately the repo hasn't been maintained/updated in a while..

**Comment by ricardo-rendoncepeda** [comment]
@PaulCapestany

I totally know where you're coming from. The biggest reason I write tutorials/tools is that there's very little information out there and I know how frustrating/difficult it is to build an iOS/OpenGL ES app from scratch as a beginner.

Jeff LaMarche's work is a valuable resource, but It's been a while since I've used that repository. I'll have a peek again and see if it can inspire any new ideas!

Since you're "totally new to all of this 3D/OpenGL stuff", here's a quick tip for fixing your Blonde Girl rendering.
1) Open the raw .obj file in Blender/Maya.
2) Export the individual objects separately (eyes, head, mouth, etc.).
3) Run mtl2opengl on each resulting .obj/.mtl file pair.
4) Import the resulting header files into Xcode and create a separate rendering loop for each object, for example:

```
- (void)glkView:(GLKView *)view drawInRect:(CGRect)rect
{
    // Clear Buffers
    glClearColor(1.0, 1.0, 1.0, 1.0);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    // Set View Matrices
    [self updateViewMatrices];

    // Render Model
    // (TODO: Write the functions called below)
    [self renderEyes];
    [self renderHead];
    [self renderMouth];
}
```

5) Most importantly,create and attach a texture to each model part (this'll be the tricky part).

And with that you'll be on your way!
